---
Name: pmtoolroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'start': StartController
    'administrator': AdminController
    'developer//$Action/$ID/$Name': 'DeveloperController'
    'DeveloperController//$Action/$ID/$Name': 'DeveloperController'
    'projectmanager//$Action/$ID/$Name': 'ProjectmanagerController'
    'ProjectmanagerController//$Action/$ID/$Name': 'ProjectmanagerController'
    'home': Page_Controller