---
Name: pmtoolroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'home': Page_Controller
    'administrator': AdminController
    'projectmanager/projects': Projectcontroller
    'developer/projects': Projectcontroller
    'developer//$Action/$ID/$Name': DeveloperController
    'DeveloperController//$Action/$ID/$Name': DeveloperController
    'projectmanager//$Action/$ID/$Name': ProjectmanagerController
    'ProjectmanagerController//$Action/$ID/$Name': ProjectmanagerController
