---
Name: pmtoolroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'start': StartController
    'administrator': AdminController
    'developer': DeveloperController
    'projectmanager': ProjectmanagerController
    'home': Page_Controller